const testMenus = [
  {
    serverId: 66,
    project_id: 'base',
    id: '/menulist',
    label: '示例菜单',
    icon: 'nested',
    compsKey: '',
    useStatus: true,
    menuType: 'rootpath',
    parentId: '',
    path: '/menulist',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 200000,
    redirect: '',
    menuLevel: 0,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 67,
    project_id: 'base',
    id: '/menulist/menu1',
    label: 'Menu1',
    icon: 'nested',
    compsKey: '',
    useStatus: true,
    menuType: 'middlepath',
    parentId: '/menulist',
    path: 'menu1',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 210000,
    redirect: '',
    menuLevel: 1,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 70,
    project_id: 'base',
    id: '/menulist/menu1/menu1-1',
    label: 'Menu1-1',
    icon: 'nested',
    compsKey: 'menu1-1',
    useStatus: true,
    menuType: 'endPoint',
    parentId: '/menulist/menu1',
    path: 'menu1-1',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 211000,
    redirect: '',
    menuLevel: 2,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 71,
    project_id: 'base',
    id: '/menulist/menu1/menu1-2',
    label: 'Menu1-2',
    icon: 'nested',
    compsKey: '',
    useStatus: true,
    menuType: 'middlepath',
    parentId: '/menulist/menu1',
    path: 'menu1-2',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 212000,
    redirect: '',
    menuLevel: 2,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 73,
    project_id: 'base',
    id: '/menulist/menu1/menu1-2/menu1-2-1',
    label: 'Menu1-2-1',
    icon: 'nested',
    compsKey: 'menu1-2-1',
    useStatus: true,
    menuType: 'endPoint',
    parentId: '/menulist/menu1/menu1-2',
    path: 'menu1-2-1',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 212100,
    redirect: '',
    menuLevel: 3,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 74,
    project_id: 'base',
    id: '/menulist/menu1/menu1-2/menu1-2-2',
    label: 'Menu1-2-2',
    icon: 'nested',
    compsKey: 'menu1-2-2',
    useStatus: true,
    menuType: 'endPoint',
    parentId: '/menulist/menu1/menu1-2',
    path: 'menu1-2-2',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 212200,
    redirect: '',
    menuLevel: 3,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 72,
    project_id: 'base',
    id: '/menulist/menu1/menu1-3',
    label: 'Menu1-3',
    icon: 'nested',
    compsKey: 'menu1-3',
    useStatus: true,
    menuType: 'endPoint',
    parentId: '/menulist/menu1',
    path: 'menu1-3',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 213000,
    redirect: '',
    menuLevel: 2,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 68,
    project_id: 'base',
    id: '/menulist/menu2',
    label: 'Menu2',
    icon: '',
    compsKey: 'menu2',
    useStatus: true,
    menuType: 'endPoint',
    parentId: '/menulist',
    path: 'menu2',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 220000,
    redirect: '',
    menuLevel: 1,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 69,
    project_id: 'base',
    id: '/menulist/menu3',
    label: 'Menu3(m2+icon)',
    icon: 'nested',
    compsKey: 'menu2',
    useStatus: true,
    menuType: 'endPoint',
    parentId: '/menulist',
    path: 'menu3',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 230000,
    redirect: '',
    menuLevel: 1,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    cTime: 1640311395,
    uTime: 0,
  },
  {
    serverId: 46,
    project_id: 'base',
    id: '/openlink',
    label: '测试外链',
    icon: 'dashboard',
    compsKey: 'LayoutIndex',
    useStatus: true,
    menuType: 'rootpath',
    parentId: '',
    path: '/openlink',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 51,
    redirect: '',
    menuLevel: 0,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: '',
    openLinkUseExternal: false,
    useExternalLink: false,
    cTime: 1640311030,
    uTime: 0,
  },
  {
    serverId: 47,
    project_id: 'base',
    id: '/openlink/to2345',
    label: '测试外链',
    icon: 'dashboard',
    compsKey: 'iframe',
    useStatus: true,
    menuType: 'endPoint',
    parentId: '/openlink',
    path: 'to2345',
    hiddenInMenu: false,
    viewHiddenMenubar: false,
    orderNum: 51,
    redirect: '',
    menuLevel: 1,
    useCache: true,
    alwaysShowInRootMenu: false,
    externalLinkUrl: 'https://www.2345.com/',
    openLinkUseExternal: true,
    useExternalLink: true,
    cTime: 1640311030,
    uTime: 0,
  },
];
export default testMenus;
