export const jsonList = [
  {
    id: 1,
    parentId: 0,
    weight: 1,
    name: '系统管理',
    icon: 'ant-design:dashboard-filled',
    permission: 'system:view',
    global: false,
    label: '系统管理',
    title: '系统管理',
    type: 1,
    path: '/system/management',
    sequence: 1,
    component: 'Layout',
    meta: {
      hideMenu: false,
      icon: 'ant-design:dashboard-filled',
      title: '系统管理',
    },
    model: null,
    status: true,
    children: [
      {
        id: 101,
        parentId: 1,
        weight: 0,
        name: '用户中心',
        icon: 'ant-design:user-outlined',
        permission: 'user:info:view',
        global: false,
        label: '用户中心',
        title: '用户中心',
        type: 1,
        path: '/system/center',
        sequence: 0,
        component: 'Layout',
        meta: {
          hideMenu: false,
          icon: 'ant-design:user-outlined',
          title: '用户中心',
        },
        model: null,
        status: true,
        children: [
          {
            id: 10101,
            parentId: 101,
            weight: 1,
            name: '用户管理',
            icon: 'heroicons-outline:user-group',
            permission: 'user:management',
            global: false,
            label: '用户管理',
            title: '用户管理',
            type: 1,
            path: '/system/user',
            sequence: 1,
            component: '/wemirr/management/user/index',
            meta: {
              hideMenu: false,
              icon: 'heroicons-outline:user-group',
              title: '用户管理',
            },
            model: null,
            status: true,
          },
          {
            id: 10102,
            parentId: 101,
            weight: 1,
            name: '组织管理',
            icon: 'codicon-organization',
            permission: 'org:view',
            global: false,
            label: '组织管理',
            title: '组织管理',
            type: 1,
            path: '/system/org',
            sequence: 1,
            component: '/wemirr/management/org/index',
            meta: {
              hideMenu: false,
              icon: 'codicon-organization',
              title: '组织管理',
            },
            model: null,
            status: true,
          },
          {
            id: 10103,
            parentId: 101,
            weight: 1,
            name: '岗位管理',
            icon: 'eos-icons:job',
            permission: 'station:management',
            global: false,
            label: '岗位管理',
            title: '岗位管理',
            type: 1,
            path: '/system/station',
            sequence: 1,
            component: '/wemirr/management/station/index',
            meta: {
              hideMenu: false,
              icon: 'eos-icons:job',
              title: '岗位管理',
            },
            model: null,
            status: true,
          },
        ],
      },
      {
        id: 102,
        parentId: 1,
        weight: 1,
        name: '权限管理',
        icon: 'ant-design:security-scan-outlined',
        permission: 'auth:view',
        global: false,
        label: '权限管理',
        title: '权限管理',
        type: 1,
        path: '/system/auth',
        sequence: 1,
        component: null,
        meta: {
          hideMenu: false,
          icon: 'ant-design:security-scan-outlined',
          title: '权限管理',
        },
        model: null,
        status: true,
        children: [
          {
            id: 10201,
            parentId: 102,
            weight: 1,
            name: '菜单管理',
            icon: 'ant-design:menu-unfold-outlined',
            permission: 'menu:view',
            global: false,
            label: '菜单管理',
            title: '菜单管理',
            type: 1,
            path: '/system/menu',
            sequence: 1,
            component: '/wemirr/management/auth/menu/index',
            meta: {
              hideMenu: false,
              icon: 'ant-design:menu-unfold-outlined',
              title: '菜单管理',
            },
            model: null,
            status: true,
          },
          {
            id: 10202,
            parentId: 102,
            weight: 1,
            name: '角色管理',
            icon: 'eos-icons:role-binding-outlined',
            permission: 'role:management',
            global: false,
            label: '角色管理',
            title: '角色管理',
            type: 1,
            path: '/system/role',
            sequence: 1,
            component: '/wemirr/management/auth/role/index',
            meta: {
              hideMenu: false,
              icon: 'eos-icons:role-binding-outlined',
              title: '角色管理',
            },
            model: null,
            status: true,
          },
        ],
      },
      {
        id: 103,
        parentId: 1,
        weight: 2,
        name: '基础数据',
        icon: 'file-icons:config-coffeescript',
        permission: 'basic:view',
        global: false,
        label: '基础数据',
        title: '基础数据',
        type: 1,
        path: '/system/basic',
        sequence: 2,
        component: null,
        meta: {
          hideMenu: false,
          icon: 'file-icons:config-coffeescript',
          title: '基础数据',
        },
        model: null,
        status: true,
        children: [
          {
            id: 10301,
            parentId: 103,
            weight: 1,
            name: '数据字典',
            icon: 'bx-bxs-data',
            permission: 'dict:management',
            global: false,
            label: '数据字典',
            title: '数据字典',
            type: 1,
            path: '/system/dictionary',
            sequence: 1,
            component: '/wemirr/management/basic/dictionary/index',
            meta: {
              hideMenu: false,
              icon: 'bx-bxs-data',
              title: '数据字典',
            },
            model: null,
            status: true,
          },
          {
            id: 10302,
            parentId: 103,
            weight: 1,
            name: '地区信息',
            icon: 'ant-design:area-chart-outlined',
            permission: 'area:view',
            global: false,
            label: '地区信息',
            title: '地区信息',
            type: 1,
            path: '/system/area',
            sequence: 1,
            component: '/wemirr/management/basic/area/index',
            meta: {
              hideMenu: false,
              icon: 'ant-design:area-chart-outlined',
              title: '地区信息',
            },
            model: null,
            status: true,
          },
        ],
      },
      {
        id: 120,
        parentId: 1,
        weight: 20,
        name: '日志管理',
        icon: 'radix-icons:activity-log',
        permission: 'log:view',
        global: false,
        label: '日志管理',
        title: '日志管理',
        type: 1,
        path: '/development/log',
        sequence: 20,
        component: null,
        meta: {
          hideMenu: false,
          icon: 'radix-icons:activity-log',
          title: '日志管理',
        },
        model: null,
        status: true,
        children: [
          {
            id: 12001,
            parentId: 120,
            weight: 1,
            name: '登录日志',
            icon: 'carbon-login',
            permission: 'log:login',
            global: false,
            label: '登录日志',
            title: '登录日志',
            type: 1,
            path: '/development/log/login',
            sequence: 1,
            component: '/wemirr/development/log/login/index',
            meta: {
              hideMenu: false,
              icon: 'carbon-login',
              title: '登录日志',
            },
            model: null,
            status: true,
          },
          {
            id: 12002,
            parentId: 120,
            weight: 2,
            name: '操作日志',
            icon: 'carbon-operation',
            permission: 'log:opt',
            global: false,
            label: '操作日志',
            title: '操作日志',
            type: 1,
            path: '/development/log/opt',
            sequence: 2,
            component: '/wemirr/development/log/opt/index',
            meta: {
              hideMenu: false,
              icon: 'carbon-operation',
              title: '操作日志',
            },
            model: null,
            status: true,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    parentId: 0,
    weight: 2,
    name: '租户中心',
    icon: 'clarity-thin-client-line',
    permission: 'tenant:view',
    global: false,
    label: '租户中心',
    title: '租户中心',
    type: 1,
    path: '/tenant',
    sequence: 2,
    component: 'Layout',
    meta: {
      hideMenu: false,
      icon: 'clarity-thin-client-line',
      title: '租户中心',
    },
    model: null,
    status: true,
    children: [
      {
        id: 201,
        parentId: 2,
        weight: 0,
        name: '租户管理',
        icon: 'clarity-thin-client-line',
        permission: 'tenant:management',
        global: false,
        label: '租户管理',
        title: '租户管理',
        type: 1,
        path: '/tenant/index',
        sequence: 0,
        component: '/wemirr/tenant/index',
        meta: {
          hideMenu: false,
          icon: 'clarity-thin-client-line',
          title: '租户管理',
        },
        model: null,
        status: true,
      },
      {
        id: 202,
        parentId: 2,
        weight: 1,
        name: '连接管理',
        icon: 'ant-design:database-filled',
        permission: null,
        global: false,
        label: '连接管理',
        title: '连接管理',
        type: 1,
        path: '/tenant/database',
        sequence: 1,
        component: '/wemirr/tenant/database/index',
        meta: {
          hideMenu: false,
          icon: 'ant-design:database-filled',
          title: '连接管理',
        },
        model: null,
        status: true,
      },
    ],
  },
  {
    id: 20,
    parentId: 0,
    weight: 20,
    name: '资源中心',
    icon: 'carbon-group-resource',
    permission: 'resource:view',
    global: false,
    label: '资源中心',
    title: '资源中心',
    type: 1,
    path: '/resource',
    sequence: 20,
    component: 'Layout',
    meta: {
      hideMenu: false,
      icon: 'carbon-group-resource',
      title: '资源中心',
    },
    model: null,
    status: true,
    children: [
      {
        id: 2001,
        parentId: 20,
        weight: 1,
        name: '文件管理',
        icon: 'akar-icons:file',
        permission: 'resource:file',
        global: false,
        label: '文件管理',
        title: '文件管理',
        type: 1,
        path: '/resource/file',
        sequence: 1,
        component: '/wemirr/resource/file/index',
        meta: {
          hideMenu: false,
          icon: 'akar-icons:file',
          title: '文件管理',
        },
        model: null,
        status: true,
      },
    ],
  },
  {
    id: 30,
    parentId: 0,
    weight: 30,
    name: '消息平台',
    icon: 'bx-bx-message-alt-dots',
    permission: null,
    global: false,
    label: '消息平台',
    title: '消息平台',
    type: 1,
    path: '/message',
    sequence: 30,
    component: 'Layout',
    meta: {
      hideMenu: false,
      icon: 'bx-bx-message-alt-dots',
      title: '消息平台',
    },
    model: null,
    status: true,
    children: [
      {
        id: 3001,
        parentId: 30,
        weight: 1,
        name: '我的消息',
        icon: 'wpf-my-topic',
        permission: 'message:my',
        global: false,
        label: '我的消息',
        title: '我的消息',
        type: 1,
        path: '/message/my',
        sequence: 1,
        component: '/wemirr/message/my/index',
        meta: {
          hideMenu: false,
          icon: 'wpf-my-topic',
          title: '我的消息',
        },
        model: null,
        status: true,
      },
      {
        id: 3002,
        parentId: 30,
        weight: 1,
        name: '发布消息',
        icon: 'codicon-repo-push',
        permission: 'message:publish',
        global: false,
        label: '发布消息',
        title: '发布消息',
        type: 1,
        path: '/message/publish',
        sequence: 1,
        component: '/wemirr/message/publish/index',
        meta: {
          hideMenu: false,
          icon: 'codicon-repo-push',
          title: '发布消息',
        },
        model: null,
        status: true,
      },
    ],
  },
  {
    id: 50,
    parentId: 0,
    weight: 50,
    name: '开发平台',
    icon: 'ant-design:appstore-add-outlined',
    permission: 'development:view',
    global: false,
    label: '开发平台',
    title: '开发平台',
    type: 1,
    path: '/development',
    sequence: 50,
    component: 'Layout',
    meta: {
      hideMenu: false,
      icon: 'ant-design:appstore-add-outlined',
      title: '开发平台',
    },
    model: null,
    status: true,
    children: [
      {
        id: 5001,
        parentId: 50,
        weight: 1,
        name: '代码生成',
        icon: 'ant-design:code-sandbox-circle-filled',
        permission: 'development:generate:code',
        global: false,
        label: '代码生成',
        title: '代码生成',
        type: 1,
        path: '/development/generate/code',
        sequence: 1,
        component: '/wemirr/development/generate/code/index',
        meta: {
          hideMenu: false,
          icon: 'ant-design:code-sandbox-circle-filled',
          title: '代码生成',
        },
        model: null,
        status: true,
      },
      {
        id: 5002,
        parentId: 50,
        weight: 2,
        name: '网关管理',
        icon: 'ant-design:gateway-outlined',
        permission: 'system:gateway:view',
        global: false,
        label: '网关管理',
        title: '网关管理',
        type: 1,
        path: '/development/gateway',
        sequence: 2,
        component: null,
        meta: {
          hideMenu: false,
          icon: 'ant-design:gateway-outlined',
          title: '网关管理',
        },
        model: null,
        status: true,
        children: [
          {
            id: 500201,
            parentId: 5002,
            weight: 1,
            name: '限流规则',
            icon: 'carbon-rule',
            permission: 'development:gateway:limit',
            global: false,
            label: '限流规则',
            title: '限流规则',
            type: 1,
            path: '/development/gateway/limit',
            sequence: 1,
            component: '/wemirr/development/gateway/limit/index',
            meta: {
              hideMenu: false,
              icon: 'carbon-rule',
              title: '限流规则',
            },
            model: null,
            status: true,
          },
          {
            id: 500202,
            parentId: 5002,
            weight: 2,
            name: '限访名单',
            icon: 'carbon-ai-status-rejected',
            permission: 'development:gateway:blacklist',
            global: false,
            label: '限访名单',
            title: '限访名单',
            type: 1,
            path: '/development/gateway/blacklist',
            sequence: 2,
            component: '/wemirr/development/gateway/blacklist/index',
            meta: {
              hideMenu: false,
              icon: 'carbon-ai-status-rejected',
              title: '限访名单',
            },
            model: null,
            status: true,
          },
          {
            id: 500203,
            parentId: 5002,
            weight: 3,
            name: '网关路由',
            icon: 'mdi-router-wireless-settings',
            permission: 'development:gateway:route',
            global: false,
            label: '网关路由',
            title: '网关路由',
            type: 1,
            path: '/development/gateway/route',
            sequence: 3,
            component: '/wemirr/development/gateway/route/index',
            meta: {
              hideMenu: false,
              icon: 'mdi-router-wireless-settings',
              title: '网关路由',
            },
            model: null,
            status: true,
          },
        ],
      },
      {
        id: 5030,
        parentId: 50,
        weight: 30,
        name: '应用管理',
        icon: 'carbon-application',
        permission: 'application:management',
        global: false,
        label: '应用管理',
        title: '应用管理',
        type: 1,
        path: '/system/application',
        sequence: 30,
        component: '/wemirr/management/application/index',
        meta: {
          hideMenu: false,
          icon: 'carbon-application',
          title: '应用管理',
        },
        model: null,
        status: true,
      },
      {
        id: 5050,
        parentId: 50,
        weight: 50,
        name: '监控中心',
        path: '/system/monitor',
        sequence: 50,
        meta: {
          hideMenu: false,
          frameSrc: 'http://localhost:9000/monitor',
          icon: 'eos-icons:monitoring',
          title: '监控中心',
        },
        icon: 'eos-icons:monitoring',
        permission: 'development:view',
        model: null,
        global: false,
        label: '监控中心',
        title: '监控中心',
        type: 1,
        status: true,
      },
      {
        id: 5060,
        parentId: 50,
        weight: 60,
        name: '注册中心',
        icon: 'simple-icons:theregister',
        permission: 'service:governance:nacos:view',
        global: false,
        label: '注册中心',
        title: '注册中心',
        type: 1,
        path: 'http://localhost:8848/nacos',
        sequence: 60,
        component: '/system/development/nacos',
        meta: {
          hideMenu: false,
          icon: 'simple-icons:theregister',
          title: '注册中心',
        },
        model: null,
        status: true,
      },
      {
        id: 5070,
        parentId: 50,
        weight: 70,
        name: '服务治理',
        icon: 'ri-government-fill',
        permission: 'nepxion:platform',
        global: false,
        label: '服务治理',
        title: '服务治理',
        type: 1,
        path: 'http://218.78.55.64:6001/platform',
        sequence: 70,
        component: '',
        meta: {
          hideMenu: false,
          icon: 'ri-government-fill',
          title: '服务治理',
        },
        model: null,
        status: true,
      },
    ],
  },
];
