export const menuFormClearItem = {
  icon: '',
  name: '',
  orderNo: 0,
  parentId: '',
  parentName: '',
  path: '',
  menuType: '',
  compType: '',
  iframeSrc: '',
  compsKey: '',
  iframeTokenType: 'none',
  useCache: true,
  menuListShow: true,
};
