import { BasicColumn, FormSchema } from '/@/components/Table';

export const getAccountColumnsCfg: BasicColumn[] = [
  {
    title: '编号',
    dataIndex: 'user_id',
    width: '70px',
    slots: { customRender: 'colUserId' },
    sorter: true,
  },
  {
    title: '账号',
    dataIndex: 'account',
    width: '120px',
    sorter: true,
  },
  {
    title: '昵称',
    dataIndex: 'nickname',
    width: '120px',
    sorter: true,
  },
  {
    title: '头像',
    defaultHidden: true,
    dataIndex: 'avatar',
    width: '120px',
    sorter: true,
  },
  {
    title: '状态',
    dataIndex: 'status',
    width: '70px',
    slots: { customRender: 'colStatus' },
    sorter: true,
  },
  {
    title: '手机号',
    dataIndex: 'phone',
    width: 120,
    sorter: true,
  },
  {
    title: '创建时间',
    dataIndex: 'created_at',
    width: 120,
    sorter: true,
  },
  {
    title: '修改时间',
    dataIndex: 'updated_at',
    width: 120,
    sorter: true,
  },
];

export const testDataList = [
  {
    user_id: 116,
    account: 'xx',
    nickname: 'xxs',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1645519091,
    created_at: 1645518964,
    updated_at: 1645519091,
    user_binds: {
      '2': 'xx',
      '3': 'xxs',
    },
    user_meta: {},
    projects: ['proj_z5'],
    default_project: 'proj_z5',
    project_roles: [],
  },
  {
    user_id: 96,
    account: 'ceshi',
    nickname: '测试宝宝',
    phone: '13800001112',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1641811406,
    last_pass_at: 1642414863,
    created_at: 1641446808,
    updated_at: 1642415678,
    user_binds: {
      '2': 'ceshi',
      '3': '测试宝宝',
      '5': '13800001112',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['operater', 'marketer'],
  },
  {
    user_id: 31,
    account: 'wangxu',
    nickname: '王旭',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947518,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'wangxu',
      '3': '王旭',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 32,
    account: 'housiyuan',
    nickname: '侯思远',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947518,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'housiyuan',
      '3': '侯思远',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 33,
    account: 'wangwenhao',
    nickname: '王文浩',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947518,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'wangwenhao',
      '3': '王文浩',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer', 'videorediter'],
  },
  {
    user_id: 34,
    account: 'wangchengqi',
    nickname: '王诚琦',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'wangchengqi',
      '3': '王诚琦',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 35,
    account: 'tangjiyuan',
    nickname: '唐纪远',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947518,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'tangjiyuan',
      '3': '唐纪远',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 36,
    account: 'yanghuifeng',
    nickname: '杨慧峰',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1640947515,
    last_pass_at: 1640947518,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'yanghuifeng',
      '3': '杨慧峰',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 37,
    account: 'zhoudongyu',
    nickname: '周东宇',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'zhoudongyu',
      '3': '周东宇',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 38,
    account: 'zhangyingnan',
    nickname: '张英男',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'zhangyingnan',
      '3': '张英男',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 39,
    account: 'lizhiqiang',
    nickname: '李志强',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'lizhiqiang',
      '3': '李志强',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 40,
    account: 'liguohui',
    nickname: '李郭辉',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'liguohui',
      '3': '李郭辉',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 41,
    account: 'lichaodu',
    nickname: '李朝都',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'lichaodu',
      '3': '李朝都',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 42,
    account: 'litaikun',
    nickname: '李泰坤',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1640947536,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'litaikun',
      '3': '李泰坤',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 43,
    account: 'liumeixin',
    nickname: '刘美昕',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446902,
    user_binds: {
      '2': 'liumeixin',
      '3': '刘美昕',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 45,
    account: 'caoliren',
    nickname: '曹立仁',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'caoliren',
      '3': '曹立仁',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 46,
    account: 'wangxusheng',
    nickname: '王旭升',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1642390092,
    last_pass_at: 1640947519,
    created_at: 1640922811,
    updated_at: 1642390092,
    user_binds: {
      '2': 'wangxusheng',
      '3': '王旭升',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 47,
    account: 'myxiaoyu',
    nickname: '马笑语',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1641781110,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641781110,
    user_binds: {
      '2': 'myxiaoyu',
      '3': '马笑语',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 48,
    account: 'wuchengyue',
    nickname: '吴成越',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'wuchengyue',
      '3': '吴成越',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 49,
    account: 'lingqiang',
    nickname: '凌强',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1641780492,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641780492,
    user_binds: {
      '2': 'lingqiang',
      '3': '凌强',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 50,
    account: 'songzhijing',
    nickname: '宋志京',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'songzhijing',
      '3': '宋志京',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 51,
    account: 'youyinhao',
    nickname: '游寅灏',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'youyinhao',
      '3': '游寅灏',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 52,
    account: 'zhangsenyi',
    nickname: '张森意',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'zhangsenyi',
      '3': '张森意',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 53,
    account: 'zouqian',
    nickname: '邹茜',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'zouqian',
      '3': '邹茜',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 54,
    account: 'sunliangmei',
    nickname: '孙亮媚',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'sunliangmei',
      '3': '孙亮媚',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 55,
    account: 'wangzhen',
    nickname: '王震',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1641781140,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641781140,
    user_binds: {
      '2': 'wangzhen',
      '3': '王震',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 56,
    account: 'zhangbuhui',
    nickname: '张步晖',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947520,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'zhangbuhui',
      '3': '张步晖',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 57,
    account: 'xiaojia',
    nickname: '肖恝',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947521,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'xiaojia',
      '3': '肖恝',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 58,
    account: 'guochengyu',
    nickname: '郭承宇',
    phone: '',
    email: '',
    status: 1,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947521,
    created_at: 1640922811,
    updated_at: 1642415388,
    user_binds: {
      '2': 'guochengyu',
      '3': '郭承宇',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 59,
    account: 'gaohaotian',
    nickname: '高昊天',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947514,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'gaohaotian',
      '3': '高昊天',
    },
    user_meta: {},
    projects: ['proj_z5'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 60,
    account: 'pengziyi',
    nickname: '彭子奕',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947514,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'pengziyi',
      '3': '彭子奕',
    },
    user_meta: {},
    projects: ['proj_z5'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 61,
    account: 'zhangcongyi',
    nickname: '张丛艺',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1642386260,
    last_pass_at: 1640947521,
    created_at: 1640922811,
    updated_at: 1642386260,
    user_binds: {
      '2': 'zhangcongyi',
      '3': '张丛艺',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 62,
    account: 'wanxiaoli',
    nickname: '万小利',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947521,
    created_at: 1640922811,
    updated_at: 1641446903,
    user_binds: {
      '2': 'wanxiaoli',
      '3': '万小利',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 4,
    account: 'dongwenqiang',
    nickname: '董文强',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1642502798,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1642502798,
    user_binds: {
      '2': 'dongwenqiang',
      '3': '董文强',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 5,
    account: 'sunqing',
    nickname: '孙青',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1641781449,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641781449,
    user_binds: {
      '2': 'sunqing',
      '3': '孙青',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer', 'topmanager'],
  },
  {
    user_id: 6,
    account: 'zhenglingling',
    nickname: '郑玲玲',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'zhenglingling',
      '3': '郑玲玲',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 7,
    account: 'lize',
    nickname: '郦泽',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'lize',
      '3': '郦泽',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 8,
    account: 'huchao',
    nickname: '胡超',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'huchao',
      '3': '胡超',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 9,
    account: 'jiapeng',
    nickname: '贾鹏',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'jiapeng',
      '3': '贾鹏',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 10,
    account: 'chenmohan',
    nickname: '陈墨涵',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1641450805,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641450805,
    user_binds: {
      '2': 'chenmohan',
      '3': '陈墨涵',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer', 'operater'],
  },
  {
    user_id: 11,
    account: 'sulilong',
    nickname: '苏立龙',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'sulilong',
      '3': '苏立龙',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 12,
    account: 'xiexianlin',
    nickname: '谢贤林',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947515,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'xiexianlin',
      '3': '谢贤林',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 13,
    account: 'liuxiangyu',
    nickname: '刘翔宇',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1641780956,
    last_pass_at: 1640947516,
    created_at: 1640922810,
    updated_at: 1641780956,
    user_binds: {
      '2': 'liuxiangyu',
      '3': '刘翔宇',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 14,
    account: 'zhangyantao',
    nickname: '张彦涛',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1642502458,
    last_pass_at: 1640947516,
    created_at: 1640922810,
    updated_at: 1642502458,
    user_binds: {
      '2': 'zhangyantao',
      '3': '张彦涛',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 15,
    account: 'suihao',
    nickname: '隋昊',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947510,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'suihao',
      '3': '隋昊',
    },
    user_meta: {},
    projects: ['proj_z5'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 16,
    account: 'luotianwei',
    nickname: '罗田唯',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1642066558,
    last_pass_at: 1642414588,
    created_at: 1640922810,
    updated_at: 1642414588,
    user_binds: {
      '2': 'luotianwei',
      '3': '罗田唯',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 17,
    account: 'jiatingting',
    nickname: '贾婷婷',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947516,
    created_at: 1640922810,
    updated_at: 1644463698,
    user_binds: {
      '2': 'jiatingting',
      '3': '贾婷婷',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: [],
  },
  {
    user_id: 18,
    account: 'zhangkai',
    nickname: '张恺',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947516,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'zhangkai',
      '3': '张恺',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['operater'],
  },
  {
    user_id: 19,
    account: 'dengjian',
    nickname: '邓坚',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'dengjian',
      '3': '邓坚',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 20,
    account: 'linzhihan',
    nickname: '林枳含',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'linzhihan',
      '3': '林枳含',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 21,
    account: 'test',
    nickname: '测试账号',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'test',
      '3': '测试账号',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 22,
    account: 'haotengview',
    nickname: '豪腾',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'haotengview',
      '3': '豪腾',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['topmanager'],
  },
  {
    user_id: 23,
    account: 'dudan',
    nickname: '杜丹',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'dudan',
      '3': '杜丹',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 24,
    account: 'xielei',
    nickname: '谢磊',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'xielei',
      '3': '谢磊',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer', 'operater'],
  },
  {
    user_id: 25,
    account: 'yangmengfan',
    nickname: '杨梦凡',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1642494616,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1642494616,
    user_binds: {
      '2': 'yangmengfan',
      '3': '杨梦凡',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 26,
    account: 'lvbinbin',
    nickname: '吕彬彬',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947517,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'lvbinbin',
      '3': '吕彬彬',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 28,
    account: 'ouliang',
    nickname: '区良',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947518,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'ouliang',
      '3': '区良',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['marketer'],
  },
  {
    user_id: 29,
    account: 'liuyanlin',
    nickname: '刘艳玲',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947518,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'liuyanlin',
      '3': '刘艳玲',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 30,
    account: 'guomiao',
    nickname: '郭淼',
    phone: '',
    email: '',
    status: 0,
    avatar: '',
    sex: 2,
    last_visit_ip: '',
    last_visit_at: 0,
    last_pass_at: 1640947518,
    created_at: 1640922810,
    updated_at: 1641446902,
    user_binds: {
      '2': 'guomiao',
      '3': '郭淼',
    },
    user_meta: {},
    projects: ['proj_z5', 'proj_topwar'],
    default_project: 'proj_z5',
    project_roles: ['videorediter'],
  },
  {
    user_id: 1,
    account: 'biadmin9527',
    nickname: 'XXOO',
    phone: '13800001111',
    email: 'asdf@rehn.con',
    status: 0,
    avatar: '',
    sex: 1,
    last_visit_ip: '103.69.152.227',
    last_visit_at: 1646295039,
    last_pass_at: 1643011856,
    created_at: 1632827283,
    updated_at: 1646295039,
    user_binds: {
      '1': 'asdf@rehn.con',
      '2': 'biadmin9527',
      '3': 'XXOO',
      '5': '13800001111',
    },
    user_meta: {},
    projects: ['base', 'proj_topwar', 'proj_z5'],
    default_project: 'proj_z5',
    project_roles: [],
  },
];

export const getSearchFormCfg: FormSchema[] = [
  {
    field: 'user_id',
    label: '用户Id',
    component: 'Input',
    colProps: { span: 8 },
  },
  {
    field: 'nickname',
    label: '用户昵称',
    component: 'Input',
    colProps: { span: 8 },
  },
  {
    field: 'status',
    label: '用户状态',
    component: 'Input',
    colProps: { span: 8 },
  },
  {
    field: 'created_at',
    label: '创建时间',
    component: 'TimePicker',
    colProps: { span: 8 },
  },
];

export const getProjsList = [
  {
    project_id: 'proj_ceshi2',
    project_name: '测试20',
    game_name: '测试20',
    order_num: 0,
    state: 0,
    created_at: 1642688356,
    updated_at: 1642746432,
  },
  {
    project_id: 'proj_ceshi1',
    project_name: '测试1',
    game_name: '测试123',
    order_num: 5,
    state: 1,
    created_at: 1642679835,
    updated_at: 1642688377,
  },
  {
    project_id: 'proj_z5',
    project_name: 'Zgrils5',
    game_name: 'Zgrils5',
    order_num: 0,
    state: 0,
    created_at: 1640662331,
    updated_at: 1640662331,
  },
  {
    project_id: 'proj_topwar',
    project_name: 'Topwar',
    game_name: 'Topwar',
    order_num: 0,
    state: 0,
    created_at: 1640662117,
    updated_at: 1640662117,
  },
  {
    project_id: 'base',
    project_name: '初始项目',
    game_name: '初始项目',
    order_num: 0,
    state: 0,
    created_at: 1632827287,
    updated_at: 1632827287,
  },
];
